### ISSUE TITLE
MVPリリース機能の確認

### ISSUE THREAD

**Issue by ashizawakazuki** [ashizawakazuki/Good-Sleep-Joy#12]
お世話になります。
以下のとおりMVPリリース時までの実装のレビューを依頼いたします。

## 各種情報
サービスの概要とMVPで検証する事柄：「Good Sleep Joy」は、「良い眠り」から「喜び」を感じていただける、睡眠サポートアプリです。 ユーザー同士が、質の高い睡眠をとるためのアイテムや習慣を共有できます。

サービス名：Good-Sleep-Joy

サービスURL：https://good-sleep-joy.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] ログアウト機能
- [x] 投稿のCRUD（登録・参照・更新・削除）機能
- [x] 共有された投稿の一覧表示、詳細ページ
- [x] 投稿時の画像アップロード
- [x] プロフィール機能

## READMEレビュー時から変更した機能
READMEには投稿機能の他に、日記機能の実装をMVPリリース時に実装することを書いたのですが、講師の方との面談で本リリースに回すことになりました。

**Comment by busitora** [comment]
ログインしていない状態で下記のようにpost編集画面にいくとエラーになります。
https://good-sleep-joy.onrender.com/item_posts/5/edit

<img width="1467" alt="スクリーンショット 0006-12-16 20 25 14" src="https://github.com/user-attachments/assets/22b14b62-1fcc-4e90-8d5b-faa986c10713" />


上記以外にも、ログインしていないユーザーのアクセスの考慮はしておきましょう。

**Comment by ashizawakazuki** [comment]
ご指摘ありがとうございます！
修正をしましたので、再度ご確認をお願いいたします。

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。目を通しておいてくださいませ！
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
