### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by ashizawakazuki** [ashizawakazuki/Good-Sleep-Joy#32]
■Webアプリの概要
「Good Sleep Joy」は、「良い眠り」から「喜び」を感じていただく、睡眠サポートアプリです。
ユーザー同士が、質の高い睡眠をとるためのアイテムや習慣を共有できます。
また、1日の最後にその日楽しかった出来事を3つ書き出すことで、毎日ポジティブな気持ちで眠りにつくことができます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：約20時間
（12/27~1/5は多めに時間を確保する予定です）

■ProjectsのURL
https://github.com/users/ashizawakazuki/projects/1/views/1

■MVPリリースまで
- [ ] rails new
- [ ] Renderにデプロイ
- [ ] トップページ
- [ ] ヘッダー・フッター
- [ ] ログイン機能 
- [ ] ユーザー登録機能
- [ ] マイページ
- [ ] アイテム投稿、詳細、編集、削除機能
- [ ] 習慣投稿、詳細、編集、削除機能
- [ ] アイテム投稿一覧
- [ ] 習慣投稿一覧
- [ ] ポジティブ3行日記作成、編集、削除機能

■MVP後
- [ ] お問い合わせ
- [ ] プライバシーポリシー
- [ ] 利用規約
- [ ] パスワードリセット
- [ ] コメント機能（アイテム投稿・習慣投稿）
- [ ] フラッシュメッセージ（新規登録、ログイン・ログアウト時以外）
- [ ] いいね機能
- [ ] ページネーション
- [ ] Xへのシェア機能

■MVPレビュー依頼予定日
予定日：2025年 1月 18日

**Comment by tarakish** [comment]
LGTMです！
投稿系のIssueが他のIssueと比較して粒度が大きい印象を受けたので、投稿の中でも更に分割できる部分があれば分割して進められると良さそうです！
